### ISSUE TITLE
pagination question

### ISSUE THREAD

**Issue by ctf0** [jhofm/flysystem-iterator#8]
hi again, i wanted to ask if there is a way to paginate the iterator to optimize the memory usage even further ?

i've searched for this but sadly no filesystem allows that, i mean its not like how database operates so you cant tell the fs to jump 10 files for example to get to the next ones without reading those first 10.

so from ur experience do u have any idea how to achieve that ? or if its even possible ?

**Comment by jhofm** [comment]
you could save memory by reading a directory index and only keeping part of it in memory and remember the position in the directory instead. but that would usually mean that you have to read the whole index again when you want to access a file that is out of bounds of what you currently remember. meaning more file system interaction, which is expensive. plus when doing that you'd have to allocate memory for everything in the directory at least temporarily. so in most cases it's probably not worth it. 
if you have control over how the files are written in the first place you can put them in automatically created subdirectories by using the first letters of a hash of the original filepath for example. having huge amounts of files in a single directory is a bad idea in most filesystems, because performance will suffer.

**Comment by ctf0** [comment]
ah okay, btw the lib works with `league/flysystem-cached-adapter` right ? if yes then no worries about the memory caching as the cache adapter take care of that automatically

**Comment by jhofm** [comment]
yup, every flysystem adapter should work

**Comment by ctf0** [comment]
awesome thanks
